# Generated by Django 5.2.14 on 2026-06-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MimicME Shop', max_length=200)),
                ('site_tagline', models.CharField(blank=True, default='Your Premier E-Commerce Platform', max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('footer_text', models.CharField(blank=True, default='Built with Django & Bootstrap', max_length=500)),
                ('contact_email', models.EmailField(blank=True, default='francis@mimicmeshop.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='+255689045666', max_length=20)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('is_setup_complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
