# Generated by Django 5.2.14 on 2026-06-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_sitesettings_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facial_login_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable Facial Login'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, default='456 Main St, Dodoma', max_length=500),
        ),
    ]
