# Generated by Django 5.2.14 on 2026-06-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_sitesettings_facial_login_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='facial_login_enabled',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='login_method',
            field=models.CharField(choices=[('both', 'Password & Face Login (Both)'), ('password_only', 'Password Only'), ('face_only', 'Face Only')], default='both', max_length=20, verbose_name='Allowed Login Method'),
        ),
    ]
