# Generated by Django 5.2.14 on 2026-06-07 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TamUtautSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pu_speeds_up', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='The system helps me complete transactions faster')),
                ('pu_improves_performance', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='The system improves my shopping performance')),
                ('pu_useful', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='The system is useful for online shopping')),
                ('peu_easy_to_learn', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='Learning to use the system is easy')),
                ('peu_easy_to_use', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='The system is easy to use')),
                ('peu_clear_interaction', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='My interaction with the system is clear and understandable')),
                ('pe_saves_time', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='The system saves me time when shopping')),
                ('pe_increases_productivity', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='The system increases my shopping productivity')),
                ('ee_effortless', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='I find the system effortless to use')),
                ('ee_easy_to_navigate', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='Navigation through the system is easy')),
                ('si_others_recommend', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='People who influence me think I should use the system')),
                ('si_peers_use', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='My peers use similar systems')),
                ('fc_resources_available', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='I have the resources needed to use the system')),
                ('fc_support_available', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='Help and support is available when I need it')),
                ('trust_system', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='I trust the system to protect my data')),
                ('trust_payment', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='I trust the payment processing')),
                ('trust_vendor', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='I trust vendors on this platform')),
                ('bi_intend_to_use', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='I intend to continue using the system')),
                ('bi_would_recommend', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], verbose_name='I would recommend the system to others')),
                ('feedback', models.TextField(blank=True, help_text='Additional comments or feedback')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('role_at_time', models.CharField(blank=True, help_text='User role when survey was taken', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TAM/UTAUT Survey',
                'verbose_name_plural': 'TAM/UTAUT Surveys',
            },
        ),
        migrations.CreateModel(
            name='TrustMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(help_text='e.g. login_trust, payment_trust, vendor_trust', max_length=100)),
                ('score', models.DecimalField(decimal_places=2, help_text='Trust score 0.00 - 5.00', max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trust Metric',
                'verbose_name_plural': 'Trust Metrics',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
