# Generated by Django 5.2.14 on 2026-06-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_refund_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='face_verified',
            field=models.BooleanField(default=False),
        ),
    ]
