# Generated by Django 5.2.14 on 2026-06-07 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biometric Session',
                'verbose_name_plural': 'Biometric Sessions',
            },
        ),
        migrations.CreateModel(
            name='FaceDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.TextField(help_text='Encrypted face embedding vector as base64 string')),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_descriptor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Descriptor',
                'verbose_name_plural': 'Face Descriptors',
            },
        ),
    ]
