# Generated by Django 5.2.14 on 2026-06-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'Order Update'), ('payment', 'Payment Update'), ('delivery', 'Delivery Update'), ('promotion', 'Promotion'), ('system', 'System'), ('contact', 'Contact Message')], max_length=20),
        ),
    ]
